[default]
account = "RLYCYMJ-ZIB04765"
user = "snuffixtrial"
password = "Test12#$"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
